go.property("follow_object_id", hash(""))
go.property("kill_after", 3)

function init(self)
	go.set_position(go.get_position(self.follow_object_id))
	msg.post("#trail_maker", "reset")

	timer.delay(self.kill_after, false, function(self)
		go.delete(self.follow_object_id)
		go.delete()
	end)
end

function update(self, dt)
	go.set_position(go.get_position(self.follow_object_id))
	msg.post("#trail_maker", "update", { dt = dt })
end
