function init(self)
	msg.post(".", "acquire_input_focus")

	go.animate(".", "position.x", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_LINEAR, 1)
end

function final(self)
end

function update(self, dt)
end

function on_input(self, action_id, action)
	if action_id == hash("click") then
		local root_pos = go.get_position(go.get_id("/go"))
		go.animate(".", "position.x", go.PLAYBACK_ONCE_FORWARD, action.x - root_pos.x, go.EASING_OUTCUBIC, 0.3)
		go.animate(".", "position.y", go.PLAYBACK_ONCE_FORWARD, action.y - root_pos.y, go.EASING_OUTCUBIC, 0.3)
	end
end
