
go.property("_position", vmath.vector3())

local function update_pos(self)
	go.set_position(self._position)
end

function init(self)
	msg.post(".", "acquire_input_focus")

	self._position = go.get_position()

	go.animate("#logo_cursor", "_position.x", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_LINEAR, 1)

	update_pos(self)
end

function final(self)
end

function update(self, dt)
	update_pos(self)
end

function on_input(self, action_id, action)
	if action_id == hash("click") then
		local root_pos = go.get_position(go.get_id("/go"))
		go.animate("#logo_cursor", "_position.x", go.PLAYBACK_ONCE_FORWARD, action.x - root_pos.x, go.EASING_OUTCUBIC, 0.3)
		go.animate("#logo_cursor", "_position.y", go.PLAYBACK_ONCE_FORWARD, action.y - root_pos.y, go.EASING_OUTCUBIC, 0.3)
	end
end
