
go.property("_position", vmath.vector3())

local function update_pos(self)
	go.set_position(self._position)
end

function init(self)
	msg.post(".", "acquire_input_focus")

	self._position = go.get_position()

	local w2 = sys.get_config("display.width") / 2
	go.animate("#logo_cursor", "_position.x", go.PLAYBACK_ONCE_FORWARD, w2, go.EASING_LINEAR, 1)

	update_pos(self)
end

function final(self)
end

function update(self, dt)
	update_pos(self)
end

function on_input(self, action_id, action)
	if action_id == hash("click") then
		go.animate("#logo_cursor", "_position.x", go.PLAYBACK_ONCE_FORWARD, action.x, go.EASING_OUTCUBIC, 0.3)
		go.animate("#logo_cursor", "_position.y", go.PLAYBACK_ONCE_FORWARD, action.y, go.EASING_OUTCUBIC, 0.3)
	end
end
