
go.property("_angle", 0)

local function update_pos(self)
	local angle = self._angle / 180 * math.pi
	local radius = 70
	go.set_position(vmath.vector3(self._angle / 6, math.sin(angle) * radius, 0) + self._default_pos)
end

function init(self)
	self._default_pos = go.get_position()

	go.animate("#logo_hyper", "_angle", go.PLAYBACK_LOOP_PINGPONG, 360 * 3, go.EASING_INOUTSINE, 5)
	update_pos(self)
end

function update(self, dt)
	update_pos(self)
end
