function init(self)
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })

	msg.post(".", "acquire_input_focus")
end

function final(self)

end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
	if action_id == hash("profile") and action.pressed then
		msg.post("@system:", "toggle_profile")
	end
end