function init(self)
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
end

function final(self)

end

function update(self, dt)
	-- Add update code here
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here
	-- Remove this function if not needed
end
